fix: try brew install docker

diff --git a/.github/workflows/trigger_build_push.yml b/.github/workflows/trigger_build_push.yml
--- a/.github/workflows/trigger_build_push.yml
+++ b/.github/workflows/trigger_build_push.yml
@@ -52,9 +52,11 @@ jobs:
       - name: Set up Docker for macOS
         if: matrix.runner == 'macos-13'
         run: |
-          brew install docker colima
-          colima start --vm-type qemu
-          sleep 30
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
       
       - name: Log in to the Container registry
         uses: docker/login-action@v3
